import { StyleSheet } from "react-native";

export const estilos = StyleSheet.create({
  telaFundo: {
    flex: 1,
    backgroundColor: "#06142b",
    padding: 14,
  },
  cartao: {
    flex: 1,
    backgroundColor: "#f5efe2",
    borderRadius: 28,
    overflow: "hidden",
    borderWidth: 3,
    borderColor: "#c79b3b",
  },
  cabecalho: {
    paddingHorizontal: 18,
    paddingVertical: 18,
    backgroundColor: "#12243f",
    borderBottomWidth: 2,
    borderBottomColor: "#c79b3b",
  },
  cabecalhoTopo: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  imagemCapitao: {
    width: 92,
    height: 92,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: "#f8e9b0",
  },
  tituloArea: {
    flex: 1,
  },
  eyebrow: {
    fontSize: 14,
    fontWeight: "700",
    color: "#f3c969",
    marginBottom: 4,
  },
  titulo: {
    fontSize: 26,
    fontWeight: "800",
    color: "#ffffff",
  },
  subtitulo: {
    fontSize: 15,
    color: "#d9e3f0",
    marginTop: 6,
  },
  principalCorpo: {
    flex: 1,
    padding: 22,
  },
  principalHero: {
    alignItems: "center",
    marginBottom: 18,
  },
  principalImagem: {
    width: "100%",
    height: 180,
    borderRadius: 22,
    marginBottom: 16,
  },
  principalTitulo: {
    fontSize: 24,
    fontWeight: "800",
    color: "#0f172a",
    textAlign: "center",
  },
  principalTexto: {
    fontSize: 15,
    lineHeight: 23,
    color: "#334155",
    textAlign: "center",
    marginTop: 10,
  },
  switchLinha: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 18,
    backgroundColor: "#fffaf0",
    borderWidth: 1,
    borderColor: "#d7c8a1",
    marginBottom: 18,
  },
  switchLabel: {
    flex: 1,
    fontSize: 15,
    fontWeight: "600",
    color: "#111827",
    marginRight: 12,
  },
  resumoBox: {
    backgroundColor: "#fffaf0",
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: "#d7c8a1",
    marginBottom: 18,
    gap: 10,
  },
  resumoItem: {
    fontSize: 14,
    lineHeight: 22,
    color: "#334155",
  },
  botoesArea: {
    gap: 12,
  },
  botao: {
    borderRadius: 18,
    paddingVertical: 14,
    paddingHorizontal: 16,
    backgroundColor: "#8b0000",
    borderWidth: 1,
    borderColor: "#f3c969",
  },
  botaoTitulo: {
    fontSize: 17,
    fontWeight: "700",
    color: "#fff6d8",
    textAlign: "center",
  },
  botaoSubtitulo: {
    fontSize: 13,
    color: "#ffd99a",
    textAlign: "center",
    marginTop: 4,
  },
  scrollConteudo: {
    padding: 18,
  },
  destaqueBox: {
    padding: 16,
    borderRadius: 18,
    marginBottom: 16,
  },
  destaqueTitulo: {
    fontSize: 18,
    fontWeight: "800",
    color: "#fff8e8",
    marginBottom: 8,
  },
  destaqueTexto: {
    fontSize: 15,
    lineHeight: 22,
    color: "#fffdf6",
  },
  crewImage: {
    width: "100%",
    height: 190,
    borderRadius: 20,
    marginBottom: 16,
  },
  secaoCard: {
    backgroundColor: "#fffaf0",
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: "#dbcda8",
    marginBottom: 16,
  },
  secaoTitulo: {
    fontSize: 19,
    fontWeight: "800",
    color: "#7c2d12",
    marginBottom: 8,
  },
  secaoTexto: {
    fontSize: 15,
    lineHeight: 23,
    color: "#374151",
  },
  listaItem: {
    fontSize: 15,
    color: "#1f2937",
    paddingVertical: 5,
  },
  rodape: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 18,
    paddingVertical: 14,
    backgroundColor: "#12243f",
    borderTopWidth: 2,
    borderTopColor: "#c79b3b",
  },
  rodapeTexto: {
    fontSize: 13,
    color: "#f8e9b0",
  },
});
