import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#f7efe7',
  },
  drawerScrollContent: {
    flexGrow: 1,
    backgroundColor: '#fff8f0',
  },
  drawerHero: {
    backgroundColor: '#8c3b2a',
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    marginBottom: 14,
    padding: 22,
  },
  drawerHeroEyebrow: {
    color: '#ffd7b0',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 1,
    marginBottom: 8,
    textTransform: 'uppercase',
  },
  drawerHeroTitle: {
    color: '#fff8f0',
    fontSize: 24,
    fontWeight: '800',
    lineHeight: 30,
    marginBottom: 8,
  },
  drawerListWrapper: {
    flex: 1,
    paddingHorizontal: 10,
  },
  listContent: {
    padding: 18,
    paddingBottom: 28,
  },
  formContent: {
    padding: 18,
    paddingBottom: 32,
  },
  headerCard: {
    backgroundColor: '#8c3b2a',
    borderRadius: 24,
    padding: 20,
    marginBottom: 18,
  },
  headerEyebrow: {
    color: '#ffd7b0',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 1,
    marginBottom: 8,
    textTransform: 'uppercase',
  },
  headerTitle: {
    color: '#fff8f0',
    fontSize: 26,
    fontWeight: '800',
    marginBottom: 8,
  },
  headerSubtitle: {
    color: '#f7dccc',
    fontSize: 15,
    lineHeight: 21,
  },
  heroImage: {
    width: '100%',
    height: 190,
    borderRadius: 24,
    marginBottom: 18,
  },
  sectionTitle: {
    color: '#402218',
    fontSize: 20,
    fontWeight: '800',
    marginBottom: 14,
  },
  menuCard: {
    backgroundColor: '#fff8f0',
    borderRadius: 22,
    padding: 18,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#ead8c9',
  },
  menuTitle: {
    color: '#402218',
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 6,
  },
  menuDescription: {
    color: '#6e5649',
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 10,
  },
  menuPrice: {
    color: '#b45309',
    fontSize: 16,
    fontWeight: '800',
  },
  sectionHeader: {
    color: '#8c3b2a',
    fontSize: 18,
    fontWeight: '800',
    marginTop: 4,
    marginBottom: 10,
  },
  placeCard: {
    backgroundColor: '#fff8f0',
    padding: 16,
    borderRadius: 18,
    marginBottom: 12,
    borderLeftWidth: 5,
    borderLeftColor: '#f2a65a',
  },
  placeText: {
    color: '#4d372d',
    fontSize: 15,
    lineHeight: 21,
  },
  fieldLabel: {
    color: '#402218',
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 10,
  },
  input: {
    backgroundColor: '#fff8f0',
    borderColor: '#dcc6b8',
    borderRadius: 16,
    borderWidth: 1,
    color: '#402218',
    fontSize: 15,
    marginBottom: 18,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  multilineInput: {
    height: 110,
    textAlignVertical: 'top',
  },
  pickerWrapper: {
    alignSelf: 'stretch',
    backgroundColor: '#fff8f0',
    borderColor: '#dcc6b8',
    borderRadius: 16,
    borderWidth: 1,
    marginBottom: 18,
    overflow: 'hidden',
  },
  picker: {
    alignSelf: 'stretch',
    backgroundColor: '#fff8f0',
    color: '#4d372d',
    height: 56,
    width: '100%',
  },
  simpleInfoText: {
    color: '#4d372d',
    fontSize: 15,
    fontWeight: '600',
  },
  switchRow: {
    alignItems: 'center',
    backgroundColor: '#fff8f0',
    borderColor: '#ead8c9',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
    padding: 16,
  },
  switchTextGroup: {
    flex: 1,
    marginRight: 16,
  },
  switchTitle: {
    color: '#402218',
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 4,
  },
  switchDescription: {
    color: '#6e5649',
    fontSize: 13,
    lineHeight: 18,
  },
  summaryCard: {
    backgroundColor: '#402218',
    borderRadius: 22,
    marginTop: 8,
    padding: 18,
  },
  summaryTitle: {
    color: '#fff8f0',
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 10,
  },
  summaryText: {
    color: '#f7dccc',
    fontSize: 14,
    lineHeight: 22,
  },
  highlightRow: {
    alignItems: 'center',
    flexDirection: 'row',
    marginBottom: 12,
  },
  highlightDot: {
    width: 10,
    height: 10,
    borderRadius: 999,
    backgroundColor: '#f2a65a',
    marginRight: 10,
  },
  highlightText: {
    color: '#4d372d',
    flex: 1,
    fontSize: 15,
    lineHeight: 21,
  },
});

export default styles;
